import pool from "../../db/connector.js";

/**
 * Create the rate_limits table and its indexes in the connected database.
 *
 * Creates a table named `rate_limits` with columns:
 * - `id` (UUID primary key, default generated by `uuid_generate_v4()`)
 * - `identifier` (text, not null)
 * - `timestamp` (bigint, not null)
 *
 * Also creates indexes `rate_limits_identifier_idx` on `identifier` and
 * `rate_limits_timestamp_idx` on `timestamp`.
 */
export default async function createRateLimitTable(){
    const res = await pool.query(`
    create table rate_limits (
    id uuid default uuid_generate_v4() primary key,
    identifier text not null,
    timestamp bigint not null
    );

    -- Index för snabb fetch
    create index rate_limits_identifier_idx on rate_limits(identifier);
    create index rate_limits_timestamp_idx on rate_limits(timestamp);

    `)
}